export const projectsOthers = [
  {
    src: '/projects/porto-web.webp',
    alt: 'My Portofolio Sites',
    name: '',
    duration: 'August - September 2025',
    description: "I designed and developed this (my) portfolio website using TypeScript and Next.js. This website serves as a space for me to showcase both my professional projects and personal creations.",
    tags: ['NextJS', 'TailwindCSS', 'Marquee'],
    linkRepo: "https://github.com/artyaaryatama/artia-portofolio.git",
    linkProd: "",
  },
  {
    src: '/projects/ot-blockchain.webp',
    alt: 'dApp for Traditional Medicine Tracking',
    name: 'Thesis Undergraduate Project',
    duration: 'September 2024 - January 2025',
    description: "For my undergraduate thesis, I built a web-based decentralized app (dApp) from scratch using ReactJS to trace and manage traditional medicine data. The system was designed to streamline Indonesia's BPOM (similar to the FDA) registration process by integrating blockchain and cloud services. I implemented Sepolia (Ethereum Testnet) as the layer for recording transaction data, ensuring tamper-proof and verifiable tracking. To simplify user verification of transaction hashes, I utilized Firebase to store and query hashes for each registration phase, while I leveraged IPFS to upload registration files and manage decentralized storage for unique package identifiers, reinforcing transparency and reliability throughout the workflow.",
    tags: [ 'ReactJS', 'Smart Contract', 'Hardhat', 'Sepolia Network', 'Metamask', 'EtherJs', 'Firabase', 'IPFS', 'Material UI', 'Sweet Alert'],
    linkRepo: "https://github.com/artyaaryatama/obat-tradisional-blockchain",
    linkProd: "https://obat-tradisional-blockchain.vercel.app",
  },
  {
    src: '/projects/ubilab.webp',
    alt: 'Build a CMS',
    name: 'Ubicom Lab UNHAS',
    duration: 'July 2023 - January 2024',
    description: "I worked on developing a content management system (CMS) for the Ubicom Lab website at Hasanuddin University, collaborating closely with the backend team. The main goal was to make the lab's news and gallery dynamic, so they could be easily managed through the CMS and displayed directly on the website.",
    tags: ['VanillaJS', 'AJAX', 'jQuery', 'Sweet Alert'],
    linkRepo: "",
    linkProd: "",
  },
  {
    src: '/projects/sigadis.webp',
    alt: 'Develop SiGadis Web',
    name: 'PLN UP3 Makassar (Internship)',
    duration: 'September 2022 - March 2023',
    description: 'I worked on SiGadis (Sistem Gardu Terdistribusi), a web application designed to monitor power distribution substations across South Sulawesi. I was responsible for designing and developing the web application, collaborating closely with the backend team to connect and process the monitoring data. The system analyzes current and power flow to provide recommendations on whether a substation is healthy, needs inspection, or requires replacement. It was built to replace the manual calculation process, making monitoring faster and more accurate.',
    tags: ['VanillaJS', 'AJAX', 'jQuery', 'Sweet Alert'],
    linkRepo: "",
    linkProd: "",
  }
]