export const projectsFreelances = [
  {
    src: '/projects/sma-athirah.webp',
    alt: 'Build landing page and CMS',
    name: 'SMA Athirah Bone',
    duration: 'June - August 2025',
    description: "During my time here, I developed a landing page and a custom CMS to manage dynamic content, including news, achievements, teacher data, and announcements. I also contributed to UI design, ensuring that the platform maintained a clean, accessible, and user-friendly experience. This was my first full-cycle project, where I took ownership of both development and deployment. I built the frontend with Next.js, integrated Supabase to handle backend needs like authentication and dynamic content, and deployed the final product using Vercel. By leveraging Supabase's built-in features, I was able to streamline backend implementation and focus on delivering a seamless experience.",
    tags: [ 'Next.js', 'shadcn/ui', 'Tailwind CSS', 'TipTap','Supabase'],
    linkRepo: "",
    linkProd: "https://smaathirahbone.sch.id",
  },
  {
    src: '/projects/cahy-petshop.webp',
    alt: 'Build a Web Dashboard',
    name: 'Cahaya Petshop',
    duration: 'December 2023 - February 2024',
    description: "At Cahaya Petshop, I built the UI for a web dashboard that makes it easier to manage all of the store's services such as pet hotel, pet grooming, and pet clinic. A key part of the system is the monitoring feature, where staff can track essential activities like feeding, drinking, temperature, urinate, defacate, and therapy schedules. My focus was on crafting a clean, user-friendly interface, while collaborating with the backend team to connect the frontend with the system's core functionalities.",
    tags: ['HTML', 'CSS', 'Vanilla JS', 'AJAX', 'jQuery'],
    linkRepo: "",
    linkProd: "",
  },
    {
    src: '/projects/sigadis.webp',
    alt: 'Develop SiGadis Web',
    name: 'PLN UP3 Makassar (Internship)',
    duration: 'September 2022 - March 2023',
    description: 'I worked on SiGadis (Sistem Gardu Terdistribusi), a web application designed to monitor power distribution substations across South Sulawesi. I was responsible for designing and developing the web application, collaborating closely with the backend team to connect and process the monitoring data. The system analyzes current and power flow to provide recommendations on whether a substation is healthy, needs inspection, or requires replacement. It was built to replace the manual calculation process, making monitoring faster and more accurate.',
    tags: ['HTML', 'CSS', 'Vanilla JS', 'AJAX', 'jQuery', 'Sweet Alert'],
    linkRepo: "",
    linkProd: "",
  },
  {
    src: '/projects/pupr-simtaru.webp',
    alt: 'Build a landing page for SIMTARU',
    name: 'PUPR Sulawesi Selatan',
    duration: 'June - October 2022',
    description: "During this project, I worked closely with the UI/UX team to translate design mockups into clean, functional frontend pages that emphasized accessibility and maintained consistency with the mobile app experience. Alongside other frontend developers, I developed several key pages of the SIMTARU (Sistem Tata Ruang) website, including the homepage, spatial planning, regulations, publications, partners, and registration. The platform serves both as a public information portal and provides a clear call-to-action to download the SIMTARU mobile app.",
    tags: [ 'HTML', 'CSS', 'Bootsrap'],
    linkRepo: "",
    linkProd: "http://simtaru.sulselprov.go.id",
  }
]